### ISSUE TITLE
Language throws an error when opening a rust project.

### ISSUE THREAD

**Issue by Folgue02** [cchharris/VS-RustAnalyzer#6]
# Main problem
The language server **doesn't get initialized** when a rust project its loaded, instead it displays an error in a pop up down at the left corner.

# How to reproduce the error
1. Open Visual Studio
2. Open a folder containing a rust project.
3. Open a rust file.

# Errors displayed by Visual Studio

## Pop-up's error
```
Task failed: Activating language client: VS-RustAnalyzer
You task failed with the message invalid value: 0, expected one of: 1, 2, 3, 4, 6, 7, 8... (up to 25)
```

## Output from language client activation failures:
```
    Task Failed - Activating language client VS-RustAnalyzer: $VS-RustAnalyzer - Sending 'initialize' request - StreamJsonRpc.RemoteMethodNotFoundException: invalid value: 0, expected one of: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.JsonRpcExtensionMethods.<SendMethodRequestWithTelemetryAsync>d__0`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<SendInitializeRequestAsync>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__114.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<TrackTaskAsync>d__115.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<ActivateLanguageClientAsync>d__124.MoveNext()
```

# Rust version, rls location etc...

## Rust version
`rustc 1.61.0 (fe5b13d68 2022-05-18)`

## Cargo version
`cargo 1.61.0 (a028ae42f 2022-04-29)`

## Rls location
`C:\Users\%USERPROFILE%\.cargo\bin\rls.exe`

## Rust analyzer path manually set in the plugin's settings
`C:\Users\%USERPROFILE%\.cargo\bin\rls.exe`

# PD
It's my first time posting an issue on github, so if I've missed anything just tell me and I'll add it. (*Or if there is something wrong that I've done like missing a configuration step or anything, tell me*).

**Comment by cchharris** [comment]
Thanks for filing this issue.

Which language server are you using?  This was intended to interface with [rust-analyzer](https://github.com/rust-lang/rust-analyzer), which is separate from [rls](https://github.com/rust-lang/rls), which it sounds like is the one you are using?

I have not tested this with rls, nor do I intend to support it in the immediate future.

Please let me know if I have made an error and you are in fact using rust-analyzer.

**Comment by Folgue02** [comment]
> *[rust-analyzer](https://github.com/rust-lang/rust-analyzer), which is separate from [rls](https://github.com/rust-lang/rls)*

My bad, I thought they were the same thing (just another way to call it or something) , since it worked on other editors that also supposedly required `rust-analyzer` in theory.
Now it works, thanks for being comprehensive :)
